### ISSUE TITLE
X in close icon is misaligned when I change the font size in the tab bar

### ISSUE THREAD

**Issue by lee-dohm** [atom/one-light-ui#104]
<img width="405" alt="screen shot 2017-07-20 at 9 46 32 am" src="https://user-images.githubusercontent.com/1038121/28429101-5e9d3232-6d30-11e7-9893-b581cf666cb2.png">

## Steps to Reproduce

1. Add the following to `styles.less`: `.tab-bar { font-size: 16px; }`
1. Save the file with <kbd>Cmd+S</kbd>

**Expected:** X in close icon to be properly aligned<br/>
**Actual:** Close icon X is off-center<br/>

### Atom

```
Atom: 1.20.0-dev-372cef218
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
```

### apm

```
apm  1.18.3
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.3

```

### OS

Mac OS X 10.12.6

## Additional Info

<details>

<summary>Installed Packages</summary>

* about
* advanced-open-file
* archive-view
* atom-2048
* atom-dark-syntax
* atom-dark-ui
* atom-light-syntax
* atom-light-ui
* autocomplete-atom-api
* autocomplete-css
* autocomplete-emojis
* autocomplete-html
* autocomplete-html-entities
* autocomplete-plus
* autocomplete-snippets
* autoflow
* autosave
* background-tips
* badges
* base16-tomorrow-dark-theme
* base16-tomorrow-light-theme
* block-travel
* bookmarks
* bracket-matcher
* chmod
* command-palette
* convert-date
* dalek
* deprecation-cop
* dev-live-reload
* docblockr
* double-tag
* encoding-selector
* exception-reporting
* file-icons
* file-type-icons
* find-and-replace
* fonts
* fuzzy-finder
* git-diff
* github
* github-atom-light-syntax
* go-to-line
* grammar-selector
* hex
* highlight-selected
* image-view
* incompatible-packages
* indentation-indicator
* keybinding-resolver
* language-c
* language-clojure
* language-coffee-script
* language-csharp
* language-css
* language-diff
* language-elixir
* language-generic-config
* language-gfm
* language-git
* language-go
* language-html
* language-hyperlink
* language-java
* language-javascript
* language-json
* language-less
* language-make
* language-mustache
* language-objective-c
* language-pegjs
* language-perl
* language-php
* language-property-list
* language-python
* language-ruby
* language-ruby-on-rails
* language-rust
* language-sass
* language-shellscript
* language-slim
* language-source
* language-sql
* language-text
* language-todo
* language-toml
* language-typescript-grammars-only
* language-xml
* language-yaml
* less-than-slash
* line-ending-selector
* link
* markdown-helper
* markdown-mindmap
* markdown-preview
* metrics
* minimap-plus
* notifications
* one-dark-syntax
* one-dark-ui
* one-light-syntax
* one-light-ui
* open-on-github
* package-generator
* package-sync
* pretty-json
* real-time
* red-wavy-underline
* right-case
* set-syntax
* settings-view
* significant-other
* snippets
* soft-wrap-indicator
* solarized-dark-syntax
* solarized-light-syntax
* sort-lines
* spell-check
* status-bar
* styleguide
* symbols-view
* tabs
* tabs-to-spaces
* timecop
* toggle-quotes
* town-crier
* tree-view
* update-package-dependencies
* welcome
* whitespace
* wrap-guide

</details>

**Comment by simurai** [comment]
Also, seeing something related in the settings:

![image](https://user-images.githubusercontent.com/378023/28490523-23a2370c-6f17-11e7-9e08-77d5f9383957.png)
