### ISSUE TITLE
how do i change the editor to white color?

### ISSUE THREAD

**Issue by anand853** [atom/one-light-ui#106]
### Description

one-light-ui

### Steps to Reproduce

i installed the theme but the editor still displayed in black color, how do i change the editor to white background

**Expected behavior:** should be in white color

**Actual behavior:** displayed in blank

**Reproduces how often:**Yes

### Versions

1.14.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by anand853** [comment]
<img width="912" alt="screen shot 2017-08-11 at 12 15 55 pm" src="https://user-images.githubusercontent.com/3404193/29222040-db508a1c-7e8e-11e7-8e77-c6e18a4b0128.png">
<img width="1150" alt="screen shot 2017-08-11 at 12 15 49 pm" src="https://user-images.githubusercontent.com/3404193/29222041-db53878a-7e8e-11e7-920f-ce998f6db6e5.png">

**Comment by 50Wliu** [comment]
That's controlled by your syntax theme (i.e. one-light-syntax).
