### ISSUE TITLE
Standalone status-bar icons not centered

### ISSUE THREAD

**Issue by 50Wliu** [atom/one-light-ui#122]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

By default, the One UI themes give all status bar icons a [right-margin of `.25em`](https://github.com/atom/one-light-ui/blob/a975e241db1cc4acc5794834f5eec827ab280127/styles/status-bar.less#L54) so that they're not pressed against text.  However, this also causes standalone status bar icons with no associated text (such as teletype) to appear uncentered.

![teletype-uncentered](https://user-images.githubusercontent.com/2766036/36386667-82d352bc-1564-11e8-8891-0b483fb004a2.png)

**Expected behavior:** Icons with associated text to have a margin; standalone icons or the last icon in the tile to not have a margin.

**Actual behavior:** All icons have margins.

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.26.0-dev-b922430c1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by simurai** [comment]
Hmm.. that's kinda hard to detect if an icon has no text next to it. There are pseudo selectors like `:only-child` or `:empty`, but since every package could have different markup, that only works in some cases.

I guess for now we have to manually override it.
