### ISSUE TITLE
Items in select-list don't get floated

### ISSUE THREAD

**Issue by idleberg** [atom/one-light-ui#137]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

One of my Atom packages makes use of `atom-select-list` to display a select list similar to the following. Pay special attention to the floated badge.

    <div class="select-list local-storage-list">
        

        <ol class="list-group">

            <li class="inline-block">
                <div class="icon icon-database">
                    Example entry
                    <div class="pull-right">
                      <span class="badge badge-info">true</span>
                  </div>
              </div>
          </li>
      </ol>
    </div>

Both, `one-dark-ui` and `one-dark-light`, display the select-list differently from about every other theme I've tried.

**Atom Light:**

![screen shot 2018-06-03 at 22 28 20](https://user-images.githubusercontent.com/1504938/40890905-914c225e-677d-11e8-8a8c-65461fd7815b.png)

**One Light:**

![screen shot 2018-06-03 at 22 28 54](https://user-images.githubusercontent.com/1504938/40890909-9b6e2462-677d-11e8-93da-76a3fac342b5.png)

This is caused by the inline-block defined [here](https://github.com/atom/one-light-ui/blob/1bab055242d374e28f396352d28d6747887a2794/styles/tree-view.less#L62) and can be fixed by setting it to `block`. However, I'm unaware of the side-effects this might have.

    .list-group .icon, .list-tree .icon {
        display: inline-block;
        height: inherit;
    }

### Steps to Reproduce

1. Create a package that uses select-list with markup similar to the snippet above (or simply install [local-store](https://atom.io/packages/local-storage)
2. Invoke the select-list (or run `Local Storage: Open Item`)

**Expected behavior:** The badges should be floated right

**Actual behavior:** The badges aren't floated at all.

**Reproduces how often:** 100%

### Versions

    $ atom --version

    Atom    : 1.27.2
    Electron: 1.7.15
    Chrome  : 58.0.3029.110
    Node    : 7.9.0

    $ apm --version

    apm  1.19.0
    npm  3.10.10
    node 6.9.5 x64
    atom 1.27.2
    python 2.7.10
    git 2.15.1

### Additional Information

Tested on macOS 10.13.5 (17F77) & Windows 10 (Build 17134.48)

**Comment by simurai** [comment]
This should be fixed in Atom `1.31`.

An alternative would be to not nest the `.pull-right` element inside the `.icon`:

```html
<li class="inline-block">
  <div class="icon icon-database">
    Example entry
  </div>
  <div class="pull-right">
    <span class="badge badge-info">true</span>
  </div>
</li>
```
