### ISSUE TITLE
fgs, why framed ??

### ISSUE THREAD

**Issue by thfrlw** [atom/one-light-ui#19]
it was the only ui i can look at, and now framing stuff made it ugly...

**Comment by thfrlw** [comment]
frame should be option, not default

**Comment by simurai** [comment]
Since the UI uses the Syntax background color, in some cases it was hard to see the active tab. Adding some padding made it easier.

I'll close this in favor of https://github.com/atom/one-dark-ui/issues/40. Adding a "compact mode" would probably look similar to the version before.
