### ISSUE TITLE
Find and Replace in a File Dialog Broken

### ISSUE THREAD

**Issue by chibicode** [atom/one-light-ui#20]
Using one-light-ui v0.5.3:

![image](https://cloud.githubusercontent.com/assets/992008/7055331/7b3e1e62-ddf7-11e4-92ac-39560e8412a3.png)

Maybe this commit was a regression?
https://github.com/atom/one-light-ui/commit/a6a3dc8424ef3091daad8f1f09636a9447338edc

**Comment by simurai** [comment]
It looks like the same issue as https://github.com/atom/one-dark-ui/issues/36.

What's your current Atom version? It should look ok in Atom `0.190.0`.

**Comment by chibicode** [comment]
@simurai yup, it's resolved once I update. Thanks!
