### ISSUE TITLE
Scrollbars are sometimes too contrasty on certain themes.

### ISSUE THREAD

**Issue by envygeeks** [atom/one-light-ui#21]
![scrollbar](https://cloud.githubusercontent.com/assets/99763/7348943/3675e03a-ecbb-11e4-855e-8d8c3ac0a7ac.png)

On my calibrated monitors the white is barely noticeable unless I disable the light detection on the screen and force the backlight to reduce but if there is something I can do in my themes to fix this I would be glad to issue a fix to my themes rather than forcing you to change your theme unless this can be considered a bug.

**Comment by simurai** [comment]
Changing it in the theme is a good idea. Maybe the opposite works better -> make the track light and the thumb dark. A darker track probably feels too strong.

**Comment by envygeeks** [comment]
I don't know if you guys use standard tracks or if I need to hit a specific class/selector.

**Comment by simurai** [comment]
It uses the [standard scrollbars](https://github.com/atom/one-light-ui/blob/master/styles/atom.less#L19-L52).

**Comment by bojidar-bg** [comment]
+1

**Comment by envygeeks** [comment]
Thanks @simurai!
