### ISSUE TITLE
Missing border on OS X 

### ISSUE THREAD

**Issue by rnarian** [atom/one-light-ui#25]
Is there any way to fix the missing border on OS X without messing with the presentation on Windows?

![missing-border-1](https://cloud.githubusercontent.com/assets/1174951/7538375/a9d09b14-f59f-11e4-8b7e-41045f03d82b.png)

I temporarily fixed it with the following css in my styles.less file:

```
.theme-one-light-ui {
  border-top: 1px solid rgba(0,0,0,.2);
}
```

![missing-border-2](https://cloud.githubusercontent.com/assets/1174951/7538377/af39131a-f59f-11e4-8260-c2eff59bb356.png)

**Comment by simurai** [comment]
Yeah, it does look better with a border. I think there is a `platform-*` class that gets added to the body and could be used.

**Comment by rnarian** [comment]
Awesome! This is what I use in my `styles.less` now:

```
.platform-darwin atom-workspace.theme-one-light-ui {
  border-top: 1px solid rgba(0,0,0,.2);
}

.platform-darwin.is-blurred atom-workspace.theme-one-light-ui {
  border-top: 1px solid rgba(0,0,0,.1);
}
```

I would've sent a pull request, but I don't really know where to put it.

**Comment by simurai** [comment]
Ok, added to `styles/atom.less`. Thanks for your suggestion.
