### ISSUE TITLE
White text on white background in Command Pallete

### ISSUE THREAD

**Issue by iharsuvorau** [atom/one-light-ui#26]
Command Pallete `Shift + Cmd + P` shows keyboard shortcuts with white text on white. 
UI Theme: One Light. 
Syntax Theme: One Light.

**Comment by mnquintana** [comment]
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/6923 and has been fixed for the next version of Atom (0.202.0).

**Comment by nicolasmccurdy** [comment]
I can confirm this with One Light in safe mode.
