### ISSUE TITLE
Why is the minimum font size 10?

### ISSUE THREAD

**Issue by drifkin** [atom/one-light-ui#32]
I like to use a Retina MBP at an unscaled resolution, but with fairly small fonts. Is there a reason the minimum font size is 10 (maybe the layout starts breaking)? Maybe the minimum could simply be recommended instead of forced.

Happy to just fork it for myself if you guys want to keep the minimum, but I figured I'd ask for anyone else who might be interested.

**Comment by simurai** [comment]
> Is there a reason the minimum font size is 10 (maybe the layout starts breaking)?

It doesn't really start breaking below 10, just that the icons have a fixed size and it starts to look odd if the text gets very small.

What min font size are you thinking about? `8px`?

You could also override the settings in your `styles.less` file with:

```css
.theme-one-light-ui {
  font-size: 8px;
}
```

**Comment by drifkin** [comment]
Yeah that's good, `8px` seems reasonable to me. Below that the file icons in the tree start overlapping. And thanks for the `styles.less` trick, I hadn't realized that everything would scale relative to that one number, should've looked at the code!

**Comment by simurai** [comment]
Ok, will be changed to `8`. Thanks for your suggestion.

**Comment by drifkin** [comment]
Awesome, thanks for changing it so quickly!
