### ISSUE TITLE
One Light UI:Black boxes the sidebar scroll bar Bug

### ISSUE THREAD

**Issue by fcharlie** [atom/one-light-ui#4]
Today I updated the ATOM to 0.156, after the installation when I found my ATOM interface is already in an open folder, appear as shown in Figure 'Next', the way I used the code from github repository git clone 'One Light UI', in via git prior to updating to 0.156 synchronize to the latest code. Normal picture as 'Pre'

*Next* 
![next](https://cloud.githubusercontent.com/assets/6904176/5390112/94d69c46-8140-11e4-9ac2-12abb2d551cf.png)

*Pre*
![pre](https://cloud.githubusercontent.com/assets/6904176/5390111/924ffeae-8140-11e4-8eb3-eaf805ad4d82.png)

When I code regression 'One-Light-UI' commit Id:91df526b44f6ecfafd4fa0efbd78c3a68acb8fd8, no error was found.

```git checkout 91df526b44f6ecfafd4fa0efbd78c3a68acb8fd8```

Ubuntu 14.10 Theme Like Yosemite

**Comment by nathansobo** [comment]
![screenshot 2015-02-10 16 24 33](https://cloud.githubusercontent.com/assets/1789/6138784/675b0046-b141-11e4-8eeb-47080a5b25af.png)

I'm seeing some weird rendering for the tree-view's scrollbar as well.

**Comment by nathansobo** [comment]
![screenshot 2015-02-10 16 26 09](https://cloud.githubusercontent.com/assets/1789/6138804/8e0769fa-b141-11e4-986c-56190cc0db5a.png)

Here's another weird state.

**Comment by simurai** [comment]
@nathansobo The `scrollbar-corner` still had transparency. It's now opaque too and same color as the background. So you shouldn't see the "black box" anymore.

**Comment by nathansobo** [comment]
:+1:
