### ISSUE TITLE
Tree view icons color

### ISSUE THREAD

**Issue by matheusssilva** [atom/one-light-ui#40]
How to change the icons' color on tree view. For me it's green/yellow.
I want the same as the example images.

**Comment by simurai** [comment]
By "example images", do you mean like the screenshots:

![screen shot 2015-10-03 at 2 28 23 pm](https://cloud.githubusercontent.com/assets/378023/10261608/1bb8d746-69db-11e5-8166-bcf4b06c1144.png)

The icons are:

- `darkish` by default
- `green` when a new file got added
- `yellow` when a file got changed

If you want them to stay dark all the time, you could override it in your `styles.less` file:

```css
.tree-view .icon::before {
  color: #282929;
}
```

**Comment by matheusssilva** [comment]
This is my color's:
![captura de tela de 2015-10-03 13 13 41](https://cloud.githubusercontent.com/assets/7414956/10263813/fa74add0-69d0-11e5-974b-639a631b9604.png)
But, I want like your.

**Comment by thomasjo** [comment]
You are seeing those green entries because they have not yet been staged and committed to your git repository. Either delete the `.git` folder if you don't want to version control your code, or stage and commit all those new (green) files.

**Comment by matheusssilva** [comment]
The solution for my problem is:

status-added{ /*Modifica cor de arquivos criados*/
  color: #575555 !important;
}

.status-modified{ /*Modifica cor de arquivos modificados*/
  color: #de4040 !important;
}

.list-tree li.list-nested-item[class*='status-modified'] > .list-item {
  /*Modifica cor de pastas modificadas*/
    color: #de4040 !important;
}

.list-tree li.list-nested-item[class*='status-added'] > .list-item {
  /*Modifica cor de pastas adicionadas*/
    color: #575555 !important;
}

The result is:

![captura de tela de 2015-10-04 11 44 29](https://cloud.githubusercontent.com/assets/7414956/10268378/4e66ee5a-6a8d-11e5-8925-d5627c084284.png)

Thanks you all
