### ISSUE TITLE
json comment has red color

### ISSUE THREAD

**Issue by brunogarett** [atom/one-light-ui#52]
Hello,

if I put in file comment then it set wrong bg color
![screen shot 2016-03-08 at 19 57 35](https://cloud.githubusercontent.com/assets/1760203/13612577/7a5d857c-e568-11e5-9cc6-d8db18c548cc.jpg)

In theme "Solarize" it works bg is none at least
![screen shot 2016-03-08 at 19 58 23](https://cloud.githubusercontent.com/assets/1760203/13612578/7a64f456-e568-11e5-97a0-aaabe91643dc.jpg)

I know that is not standard "allowed comments in json"

Q it is possible fix it?

Bruno

**Comment by 50Wliu** [comment]
Please see the discussion over at atom/language-json#28 and atom/language-json#29 regarding comments in JSON.
