### ISSUE TITLE
With status bar extending entire width, there is no visual separator between status-bar and tree-view

### ISSUE THREAD

**Issue by lee-dohm** [atom/one-light-ui#55]
Even if there is the same background color between the text editor and the status bar, there is the line separating the two, so it is obvious where one ends and the other begins. This isn't the case with the tree-view:

<img width="602" alt="obvious" src="https://cloud.githubusercontent.com/assets/1038121/13900142/99ab9d22-edbc-11e5-9681-009ac3e88065.png">

How I discovered this, is I had a screen that looked like this:

<img width="398" alt="looks-like-tree-view-has-bug" src="https://cloud.githubusercontent.com/assets/1038121/13900150/a45c5428-edbc-11e5-8cfe-6465dedcbe3f.png">

And I thought the tree-view was broken because the last item was missing until I remembered that the status bar extends the width of the window now.

I'm not sure if there is something that should be done about this. Or something good that could be done and still maintain the visual style. But I trust that others know more than I do about these things :grinning:

**Comment by lee-dohm** [comment]
Oh, and this can only be replicated obviously when there is no text editor open because then it looks like this:

<img width="383" alt="screen shot 2016-03-19 at 10 26 18 am" src="https://cloud.githubusercontent.com/assets/1038121/13900174/0ca7db24-edbd-11e5-9bcc-d9ddeb1457b8.png">

**Comment by simurai** [comment]
:+1: We could add a border under the tree-view? And maybe also change the background?

**Comment by lee-dohm** [comment]
Hmmmm ... I was just playing around with this and it appears that at smaller window sizes, the borders turn into separators. For example there's this small window size:

![small-window](https://cloud.githubusercontent.com/assets/1038121/13940480/f30430fc-ef9a-11e5-8dbe-35be9ed39dff.png)

And then at a larger window size:

![large-window](https://cloud.githubusercontent.com/assets/1038121/13940502/2c149e54-ef9b-11e5-9bf7-1f19806ba387.png)

So maybe just a separator between the tree-view and the status-bar at small sizes and then a border around tree-view, similar to the editor area, at larger window sizes? I think a subtle shade change between the status-bar and the other areas would be good too.

**Comment by simurai** [comment]
Ya, in "compact" mode, just a border is fine:

![screen shot 2016-03-22 at 2 15 44 pm](https://cloud.githubusercontent.com/assets/378023/13942987/c2ce4c46-f03b-11e5-8dab-62f845cd7b9c.png)

Then for "spacious" mode, adding a border around the whole tree-view would be an option, but maybe a bit too "heavy"? Alternatively, the border could just fade out at the left side. So it would still feel "airy". Similar to the tabs divider.

![screen shot 2016-03-22 at 2 32 14 pm](https://cloud.githubusercontent.com/assets/378023/13942991/c90de67a-f03b-11e5-86d6-99e91a16cf99.png)

**Comment by lee-dohm** [comment]
Yeah, I like that. I think the airy feeling is fine because while I may not normally see it consciously, if I looked closer I would.

**Comment by simurai** [comment]
Ok, let's merge that. I also tried out separating the status-bar from the editor:

![screen shot 2016-03-22 at 2 12 53 pm](https://cloud.githubusercontent.com/assets/378023/13972556/131feb18-f0dd-11e5-97c0-07acdb9071be.png)

But that feels a bit too strong. We might could try it again once the title bar can be styled.
