### ISSUE TITLE
“Minimum” Tab Sizing Visual Bug

### ISSUE THREAD

**Issue by wjk** [atom/one-light-ui#59]
I just updated to Atom 1.8.0, and now the One themes default to “Auto” sizing (previously they used “Even” sizing). This threw me for a moment, and I was halfway through typing a bug report about this change when I realized that I should check the One theme settings. However, there is still one issue here: The close button or unsaved-changes dot now overlaps the edge of the text, which looks bad to me. (See screenshot below.) Is there any way to change this? Thanks!

![atom bug](https://cloud.githubusercontent.com/assets/1915951/15880383/be7a3f1e-2cfa-11e6-8b34-f0ec7b6bb57b.png)

**Comment by 50Wliu** [comment]
@wjk Make sure you have nothing in your `styles.less` file.

**Comment by wjk** [comment]
I have some code in my `styles.less`, but it all amounts to comments and otherwise-empty CSS blocks. Here's the code:

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
```

**Comment by simurai** [comment]
I can reproduce this.

The "unsaved-changes dot" could use the same "fade" as the closing X. Or maybe repositioned a bit (top?) so that it doesn't cover any text.
