### ISSUE TITLE
One Light (and One Dark) UI theme doesn't show name of opened file

### ISSUE THREAD

**Issue by i-svr** [atom/one-light-ui#72]
One Light (and One Dark) UI theme doesn't show name of opened file
It will have no names for opened tabs. It doesn't matter if it is an opened file or a preferences tab. Tabs are blank all the time. But if i resize Atom's window to lower size, tab's size gets smaller and name of opened file appears (like it should). Tab sizing set to "Auto". Screen resolution is 1280x1024.
If i set Tab sizing to "Minimum", tab names will appear, although they vanish when i hover mouse cursor upon them.

**Reproduction Steps:**
Install Atom 1.10.0 on Slackware 14.2 GNU/Linux distro (32 bit) using slackbuild from https://slackbuilds.org/repository/14.2/development/atom/.
Start up Atom fullscreen. By default theme is One Light (or One Dark), if not - select it in settings.
Tabs will have blank names.

**Expected behavior:**
Tabs should have names of opened files.

**Screenshots**
Blank tabs:
http://imgur.com/a/jNRlW

**Atom version:**
1.10.0

**OS and version:**
Slackware 14.2

**Installed packages:**
$ ./apm list
Built-in Atom Packages (89)
├── about@1.5.3
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-grammar-test@0.6.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.44.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.39.0
├── find-and-replace@0.201.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.2
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.2
├── language-csharp@0.12.1
├── language-css@0.37.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.42.1
├── language-html@0.45.1
├── language-hyperlink@0.16.0
├── language-java@0.23.0
├── language-javascript@0.119.0
├── language-json@0.18.2
├── language-less@0.29.5
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.2
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.69.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.56.0
├── language-shellscript@0.22.4
├── language-source@0.9.0
├── language-sql@0.23.0
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.9
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── notifications@0.65.0
├── one-dark-syntax@1.3.0
├── one-dark-ui@1.5.0
├── one-light-syntax@1.3.0
├── one-light-ui@1.5.0
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.241.2
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.47.0
├── symbols-view@0.113.0
├── tabs@0.100.2
├── timecop@0.33.2
├── tree-view@0.208.2
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.33.0
└── wrap-guide@0.38.1

Community Packages (0) /home/shagrath/.atom/packages
└── (empty)

└── (empty)

$

**Comment by 50Wliu** [comment]
@i-svr Can you paste the output of `atom --version` here?

**Comment by thomasjo** [comment]
The SlackBuilds stuff is not using official sources;
https://slackbuilds.org/repository/14.2/development/atom/

The author of that third-party package might have screwed something up; swapped out Electron or something along those lines.

**Comment by i-svr** [comment]
@50Wliu, here it is:
$ atom --version
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$

@thomasjo, i would have used official source, but it provides only 64bit builds, unfortunately. :/

**Comment by i-svr** [comment]
I've got problem fixed.
Looks like i had some kind of conflict on my system. Have no idea what have resolved it (system update or something else?), but it's ok now.
