### ISSUE TITLE
Improve contrast of badges on dark backgrounds

### ISSUE THREAD

**Issue by simurai** [atom/one-light-ui#75]
**Problem:** When using a `.badge` on a background from a dark syntax theme, contrast suffers.

<img width="360" alt="screen_shot_2016-09-19_at_4 18 53_pm_720" src="https://cloud.githubusercontent.com/assets/378023/18654054/2849aedc-7f19-11e6-9bd6-c96f1fa8f44c.png">

**Solution:** Change the [@background-color-selected variable](https://github.com/atom/one-light-ui/blob/master/styles/ui-variables.less#L32) to **not** use transparency.

It won't look as subtle, but at least it's readable.

![screen shot 2016-09-20 at 9 46 43 am](https://cloud.githubusercontent.com/assets/378023/18654058/2ee23340-7f19-11e6-97a5-699c72247e91.png)

**Concerns:** I think initially, transparency was used to make it more flexible with different backgrounds, but that only works when they are light too.

**Comment by matthewwithanm** [comment]
I don't think it's quite that simple…the "hi" message in the example uses [.highlight-info](https://github.com/atom/one-light-ui/blob/v1.6.1/styles/text.less#L69-L75).

**Comment by simurai** [comment]
Right.. the `.highlight` classes also shouldn't use transparency. Should be fixed in `1.12`.

**Comment by matthewwithanm** [comment]
Thanks! ❤️
